### ISSUE TITLE
Add Media Queries

### ISSUE THREAD

**Issue by elaewin** [robert-hatfield/portfolio#7]
User Story: "As a visitor, I want the primary nav to be responsive, so that I can get around using any device."

Technical Requirements:
* Use mobile-first design principles when adding CSS.
* Add new styles in any media queries as needed to make the page look good on desktop screens.

**Comment by robert-hatfield** [comment]
Media queries were added in commit b84c62a806c31fe91024d09ab76a4a0be94e2de0.
Some subsequent changes were needed to ensure no unexpected behavior.
